name: 'Setup Node.js'
description: 'Setup Node.js with npm and cache'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci